### ISSUE TITLE
BUG: 100% CPU utilization - busy waiting?

### ISSUE THREAD

**Issue by pawelkobojek** [Miksus/rocketry#37]
Thanks for sharing this amazing software.

**Describe the bug**
Running Red Engine causes 100% CPU utilization. Maybe it's busy waiting?

**To Reproduce**
This simple app prints "Hello World" every 1 minute.

```python
from redengine import RedEngine
app = RedEngine()

@app.task("every 1 minute")
def main():
    print("Hello World")

if __name__ == "__main__":
    app.run()
```

**Expected behavior**
CPU not utilized at all while waiting between running tasks.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/4778065/177569333-c80ca769-091e-4f95-ac45-e5d493e148bb.png)

**Desktop (please complete the following information):**
 - OS: macOS 12.3, Linux (5.4.0-100-generic, Ubuntu, x86_64)
 - Python version 3.10.4

**Additional context**
If there's some misconfiguration on my side I'd be grateful for tips.

**Comment by Miksus** [comment]
Thanks, it's always nice to hear people like it!

By default the tasks are run as processes which confuse some. Probably we should have a poll at some point which should be preferred. But this does not explain it as it creates the process every 1 minute and the task is minimal.

However, this is probably due to that the hibernating is by default non-existent (it checks conditions aggressively constantly). You can throttle the scheduler using:

```python
app = RedEngine(config={'cycle_sleep': 2})
```
Seems this configuration is ``int`` accidentally so it's a bug at least in this perspective (this is passed to ``time.sleep`` and it seems to support floats). I'm not sure if we should have a non-zero default to prevent the resource hogging. Basically this means the scheduler waits this amount of seconds every time it goes through _cycle_ which is looping a set of tasks.

Also, does this help to set this to one, for example? This is also undocumented (as the library is quite new).
